tap "homebrew/services"
brew "aws-c-s3"
brew "awscli"
brew "doctl"
brew "fd"
brew "fzf"
brew "node"
brew "gemini-cli"
brew "gh"
brew "gitleaks"
<<<<<<< Updated upstream
brew "go"
brew "golangci-lint"
=======
brew "googleworkspace-cli"
>>>>>>> Stashed changes
brew "gum"
brew "shared-mime-info"
brew "imagemagick"
brew "lazygit"
brew "libgit2"
brew "libmagic"
brew "libpq"
brew "libyaml"
brew "luarocks"
brew "mise"
brew "neovim"
brew "openfortivpn"
brew "openslide"
brew "openvpn"
brew "postgresql@14", restart_service: :changed
brew "rclone"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "vips"
brew "wireguard-tools"
brew "zplug"
cask "1password-cli"
cask "alacritty"
cask "gcloud-cli"
cask "google-ads-editor"
cask "ngrok"
